# Generated by Django 2.2.dev20180611123309 on 2018-07-02 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('platform_version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('cdat_info_version', models.CharField(blank=True, max_length=64)),
                ('source_version', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('sleep', models.CharField(blank=True, max_length=64)),
                ('pid', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('domain', models.CharField(blank=True, max_length=64)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
